name: Build-Release-Images
on:
  push:
    tags:
      - 'v*'
      - 'snapshot*'
  pull_request:
  workflow_dispatch: {}
jobs:
  build-release-images:
    name: Build and Release Firmware Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          key: downloads-${{ hashFiles('Makefile') }}
          path: |
            openwrt-*.tar.xz
            firmware-utils-master.tar.gz
            linux-include/**
      - name: Build firmware images
        run: 'make images CURL_OPTS="-s"'
      - uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            openwrt-imagebuilder-*/bin/targets/*/*/openwrt-*.bin
            openwrt-imagebuilder-*/bin/targets/*/*/openwrt-*.manifest
          retention-days: 7
      - name: Release
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v2
        with:
          body: |
            Automated release. Please see the project README.md for more information.

            [Build logs.](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          prerelease: True
          files: |
            openwrt-imagebuilder-*/bin/targets/*/*/openwrt-*.bin
            openwrt-imagebuilder-*/bin/targets/*/*/openwrt-*.manifest
            openwrt-imagebuilder-*/bin/targets/*/*/sha256sums
            openwrt-imagebuilder-*/bin/targets/*/*/profiles.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
